---
development:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_image_support: <%= ENV["static_image_support"] %>

production:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_image_support: <%= ENV["static_image_support"] %>

test:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_image_support: <%= ENV["static_image_support"] %>
