development:
  consumer_key: qot1au7JSBAIYVRJmC931w
  consumer_secret: nCTXkzwIfHw4WzYAuJ9YG8KVwwJTXqisB4aRZL10bA

production:
  consumer_key: ZyIZ9kzpjBTeIIW1poyyNA
  consumer_secret: OkaNymukhgn6OZ5lecUPQLFGGdq5g4G2bWdcQQfqc